#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 102
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 13
#define PRODUCTION_ID_COUNT 9

enum {
  sym_text = 1,
  anon_sym_if = 2,
  anon_sym_elseif = 3,
  anon_sym_else = 4,
  anon_sym_end = 5,
  anon_sym_range = 6,
  sym_pipeline_stub = 7,
  sym_comment = 8,
  anon_sym_LBRACE_LBRACE = 9,
  anon_sym_DASH = 10,
  anon_sym_DASH2 = 11,
  anon_sym_RBRACE_RBRACE = 12,
  sym_template = 13,
  sym__block = 14,
  sym__action = 15,
  sym__comment_action = 16,
  sym__pipeline_action = 17,
  sym_if_action = 18,
  sym_range_action = 19,
  sym__pipeline = 20,
  sym__left_delimiter = 21,
  sym__right_delimiter = 22,
  aux_sym_template_repeat1 = 23,
  aux_sym_if_action_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_text] = "text",
  [anon_sym_if] = "if",
  [anon_sym_elseif] = "else if",
  [anon_sym_else] = "else",
  [anon_sym_end] = "end",
  [anon_sym_range] = "range",
  [sym_pipeline_stub] = "pipeline_stub",
  [sym_comment] = "comment",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_DASH] = "- ",
  [anon_sym_DASH2] = " -",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [sym_template] = "template",
  [sym__block] = "_block",
  [sym__action] = "_action",
  [sym__comment_action] = "_comment_action",
  [sym__pipeline_action] = "_pipeline_action",
  [sym_if_action] = "if_action",
  [sym_range_action] = "range_action",
  [sym__pipeline] = "_pipeline",
  [sym__left_delimiter] = "_left_delimiter",
  [sym__right_delimiter] = "_right_delimiter",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_if_action_repeat1] = "if_action_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_text] = sym_text,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_range] = anon_sym_range,
  [sym_pipeline_stub] = sym_pipeline_stub,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DASH2] = anon_sym_DASH2,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [sym_template] = sym_template,
  [sym__block] = sym__block,
  [sym__action] = sym__action,
  [sym__comment_action] = sym__comment_action,
  [sym__pipeline_action] = sym__pipeline_action,
  [sym_if_action] = sym_if_action,
  [sym_range_action] = sym_range_action,
  [sym__pipeline] = sym__pipeline,
  [sym__left_delimiter] = sym__left_delimiter,
  [sym__right_delimiter] = sym__right_delimiter,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_if_action_repeat1] = aux_sym_if_action_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_range] = {
    .visible = true,
    .named = false,
  },
  [sym_pipeline_stub] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym__action] = {
    .visible = false,
    .named = true,
  },
  [sym__comment_action] = {
    .visible = false,
    .named = true,
  },
  [sym__pipeline_action] = {
    .visible = false,
    .named = true,
  },
  [sym_if_action] = {
    .visible = true,
    .named = true,
  },
  [sym_range_action] = {
    .visible = true,
    .named = true,
  },
  [sym__pipeline] = {
    .visible = false,
    .named = true,
  },
  [sym__left_delimiter] = {
    .visible = false,
    .named = true,
  },
  [sym__right_delimiter] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_action_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alternative = 1,
  field_body = 2,
  field_condition = 3,
  field_consequence = 4,
  field_option = 5,
  field_range = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_option] = "option",
  [field_range] = "range",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 4},
  [2] = {.index = 4, .length = 2},
  [3] = {.index = 6, .length = 2},
  [4] = {.index = 8, .length = 4},
  [5] = {.index = 12, .length = 2},
  [6] = {.index = 14, .length = 3},
  [7] = {.index = 17, .length = 3},
  [8] = {.index = 20, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_condition, 0, .inherited = true},
    {field_condition, 1, .inherited = true},
    {field_option, 0, .inherited = true},
    {field_option, 1, .inherited = true},
  [4] =
    {field_condition, 2},
    {field_consequence, 4},
  [6] =
    {field_body, 4},
    {field_range, 2},
  [8] =
    {field_condition, 2},
    {field_condition, 5, .inherited = true},
    {field_consequence, 4},
    {field_option, 5, .inherited = true},
  [12] =
    {field_condition, 2},
    {field_option, 4},
  [14] =
    {field_alternative, 8},
    {field_condition, 2},
    {field_consequence, 4},
  [17] =
    {field_alternative, 8},
    {field_body, 4},
    {field_range, 2},
  [20] =
    {field_alternative, 9},
    {field_condition, 2},
    {field_condition, 5, .inherited = true},
    {field_consequence, 4},
    {field_option, 5, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'p') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(9);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'p') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(9);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') SKIP(2)
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'p') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(9);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(46);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(44);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'p') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'p') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(40);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(36);
      END_STATE();
    case 17:
      if (lookahead == 'f') ADVANCE(37);
      END_STATE();
    case 18:
      if (lookahead == 'g') ADVANCE(13);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(28);
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(29);
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(12);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 30:
      if (lookahead == '{') ADVANCE(45);
      END_STATE();
    case 31:
      if (lookahead == '}') ADVANCE(48);
      END_STATE();
    case 32:
      if (eof) ADVANCE(33);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_elseif);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == ' ') ADVANCE(20);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_range);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_pipeline_stub);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DASH2);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 32},
  [2] = {.lex_state = 32},
  [3] = {.lex_state = 32},
  [4] = {.lex_state = 32},
  [5] = {.lex_state = 32},
  [6] = {.lex_state = 32},
  [7] = {.lex_state = 32},
  [8] = {.lex_state = 32},
  [9] = {.lex_state = 32},
  [10] = {.lex_state = 32},
  [11] = {.lex_state = 32},
  [12] = {.lex_state = 32},
  [13] = {.lex_state = 32},
  [14] = {.lex_state = 32},
  [15] = {.lex_state = 32},
  [16] = {.lex_state = 32},
  [17] = {.lex_state = 32},
  [18] = {.lex_state = 32},
  [19] = {.lex_state = 32},
  [20] = {.lex_state = 32},
  [21] = {.lex_state = 32},
  [22] = {.lex_state = 32},
  [23] = {.lex_state = 32},
  [24] = {.lex_state = 32},
  [25] = {.lex_state = 32},
  [26] = {.lex_state = 32},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 32},
  [48] = {.lex_state = 32},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 32},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 32},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 32},
  [55] = {.lex_state = 32},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 32},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 32},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 32},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 32},
  [86] = {.lex_state = 32},
  [87] = {.lex_state = 32},
  [88] = {.lex_state = 32},
  [89] = {.lex_state = 32},
  [90] = {.lex_state = 32},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 32},
  [94] = {.lex_state = 32},
  [95] = {.lex_state = 32},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elseif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_range] = ACTIONS(1),
    [sym_pipeline_stub] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_DASH2] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
  },
  [1] = {
    [sym_template] = STATE(100),
    [sym__block] = STATE(5),
    [sym__action] = STATE(5),
    [sym__comment_action] = STATE(5),
    [sym__pipeline_action] = STATE(5),
    [sym_if_action] = STATE(5),
    [sym_range_action] = STATE(5),
    [sym__left_delimiter] = STATE(41),
    [aux_sym_template_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_text] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(9), 1,
      sym_text,
    STATE(27), 1,
      sym__left_delimiter,
    STATE(44), 1,
      aux_sym_if_action_repeat1,
    STATE(26), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [22] = 5,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(9), 1,
      sym_text,
    STATE(28), 1,
      sym__left_delimiter,
    STATE(83), 1,
      aux_sym_if_action_repeat1,
    STATE(26), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [44] = 5,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      sym_text,
    ACTIONS(16), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(41), 1,
      sym__left_delimiter,
    STATE(4), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [66] = 5,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym_text,
    STATE(41), 1,
      sym__left_delimiter,
    STATE(4), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [88] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(23), 1,
      sym_text,
    STATE(42), 1,
      sym__left_delimiter,
    STATE(2), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [107] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(25), 1,
      sym_text,
    STATE(42), 1,
      sym__left_delimiter,
    STATE(13), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [126] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(27), 1,
      sym_text,
    STATE(42), 1,
      sym__left_delimiter,
    STATE(20), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [145] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(29), 1,
      sym_text,
    STATE(42), 1,
      sym__left_delimiter,
    STATE(14), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [164] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(31), 1,
      sym_text,
    STATE(42), 1,
      sym__left_delimiter,
    STATE(15), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [183] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(33), 1,
      sym_text,
    STATE(42), 1,
      sym__left_delimiter,
    STATE(16), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [202] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(9), 1,
      sym_text,
    STATE(39), 1,
      sym__left_delimiter,
    STATE(26), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [221] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(9), 1,
      sym_text,
    STATE(38), 1,
      sym__left_delimiter,
    STATE(26), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [240] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(9), 1,
      sym_text,
    STATE(37), 1,
      sym__left_delimiter,
    STATE(26), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [259] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(9), 1,
      sym_text,
    STATE(34), 1,
      sym__left_delimiter,
    STATE(26), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [278] = 4,
    ACTIONS(9), 1,
      sym_text,
    ACTIONS(35), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(30), 1,
      sym__left_delimiter,
    STATE(26), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [297] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(37), 1,
      sym_text,
    STATE(42), 1,
      sym__left_delimiter,
    STATE(3), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [316] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(39), 1,
      sym_text,
    STATE(42), 1,
      sym__left_delimiter,
    STATE(21), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [335] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(41), 1,
      sym_text,
    STATE(42), 1,
      sym__left_delimiter,
    STATE(23), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [354] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(9), 1,
      sym_text,
    STATE(36), 1,
      sym__left_delimiter,
    STATE(26), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [373] = 4,
    ACTIONS(9), 1,
      sym_text,
    ACTIONS(35), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(32), 1,
      sym__left_delimiter,
    STATE(26), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [392] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(43), 1,
      sym_text,
    STATE(42), 1,
      sym__left_delimiter,
    STATE(24), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [411] = 4,
    ACTIONS(9), 1,
      sym_text,
    ACTIONS(45), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(42), 1,
      sym__left_delimiter,
    STATE(26), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [430] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(9), 1,
      sym_text,
    STATE(40), 1,
      sym__left_delimiter,
    STATE(26), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [449] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(47), 1,
      sym_text,
    STATE(42), 1,
      sym__left_delimiter,
    STATE(12), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [468] = 4,
    ACTIONS(16), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(49), 1,
      sym_text,
    STATE(42), 1,
      sym__left_delimiter,
    STATE(26), 7,
      sym__block,
      sym__action,
      sym__comment_action,
      sym__pipeline_action,
      sym_if_action,
      sym_range_action,
      aux_sym_template_repeat1,
  [487] = 8,
    ACTIONS(52), 1,
      anon_sym_if,
    ACTIONS(54), 1,
      anon_sym_elseif,
    ACTIONS(56), 1,
      anon_sym_else,
    ACTIONS(58), 1,
      anon_sym_end,
    ACTIONS(60), 1,
      anon_sym_range,
    ACTIONS(62), 1,
      sym_pipeline_stub,
    ACTIONS(64), 1,
      sym_comment,
    STATE(75), 1,
      sym__pipeline,
  [512] = 8,
    ACTIONS(52), 1,
      anon_sym_if,
    ACTIONS(54), 1,
      anon_sym_elseif,
    ACTIONS(60), 1,
      anon_sym_range,
    ACTIONS(62), 1,
      sym_pipeline_stub,
    ACTIONS(64), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_else,
    ACTIONS(68), 1,
      anon_sym_end,
    STATE(75), 1,
      sym__pipeline,
  [537] = 3,
    ACTIONS(72), 1,
      anon_sym_else,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(70), 6,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_end,
      anon_sym_range,
      sym_pipeline_stub,
      sym_comment,
  [552] = 7,
    ACTIONS(52), 1,
      anon_sym_if,
    ACTIONS(60), 1,
      anon_sym_range,
    ACTIONS(62), 1,
      sym_pipeline_stub,
    ACTIONS(64), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_else,
    ACTIONS(78), 1,
      anon_sym_end,
    STATE(75), 1,
      sym__pipeline,
  [574] = 2,
    ACTIONS(80), 1,
      anon_sym_DASH,
    ACTIONS(70), 6,
      anon_sym_if,
      anon_sym_else,
      anon_sym_end,
      anon_sym_range,
      sym_pipeline_stub,
      sym_comment,
  [586] = 7,
    ACTIONS(52), 1,
      anon_sym_if,
    ACTIONS(60), 1,
      anon_sym_range,
    ACTIONS(62), 1,
      sym_pipeline_stub,
    ACTIONS(64), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_else,
    ACTIONS(84), 1,
      anon_sym_end,
    STATE(75), 1,
      sym__pipeline,
  [608] = 2,
    ACTIONS(88), 1,
      anon_sym_else,
    ACTIONS(86), 6,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_end,
      anon_sym_range,
      sym_pipeline_stub,
      sym_comment,
  [620] = 6,
    ACTIONS(52), 1,
      anon_sym_if,
    ACTIONS(60), 1,
      anon_sym_range,
    ACTIONS(62), 1,
      sym_pipeline_stub,
    ACTIONS(64), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_end,
    STATE(75), 1,
      sym__pipeline,
  [639] = 1,
    ACTIONS(86), 6,
      anon_sym_if,
      anon_sym_else,
      anon_sym_end,
      anon_sym_range,
      sym_pipeline_stub,
      sym_comment,
  [648] = 6,
    ACTIONS(52), 1,
      anon_sym_if,
    ACTIONS(60), 1,
      anon_sym_range,
    ACTIONS(62), 1,
      sym_pipeline_stub,
    ACTIONS(64), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_end,
    STATE(75), 1,
      sym__pipeline,
  [667] = 6,
    ACTIONS(52), 1,
      anon_sym_if,
    ACTIONS(60), 1,
      anon_sym_range,
    ACTIONS(62), 1,
      sym_pipeline_stub,
    ACTIONS(64), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_end,
    STATE(75), 1,
      sym__pipeline,
  [686] = 6,
    ACTIONS(52), 1,
      anon_sym_if,
    ACTIONS(60), 1,
      anon_sym_range,
    ACTIONS(62), 1,
      sym_pipeline_stub,
    ACTIONS(64), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_end,
    STATE(75), 1,
      sym__pipeline,
  [705] = 6,
    ACTIONS(52), 1,
      anon_sym_if,
    ACTIONS(60), 1,
      anon_sym_range,
    ACTIONS(62), 1,
      sym_pipeline_stub,
    ACTIONS(64), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_end,
    STATE(75), 1,
      sym__pipeline,
  [724] = 6,
    ACTIONS(52), 1,
      anon_sym_if,
    ACTIONS(60), 1,
      anon_sym_range,
    ACTIONS(62), 1,
      sym_pipeline_stub,
    ACTIONS(64), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_end,
    STATE(75), 1,
      sym__pipeline,
  [743] = 5,
    ACTIONS(102), 1,
      anon_sym_if,
    ACTIONS(104), 1,
      anon_sym_range,
    ACTIONS(106), 1,
      sym_pipeline_stub,
    ACTIONS(108), 1,
      sym_comment,
    STATE(66), 1,
      sym__pipeline,
  [759] = 5,
    ACTIONS(52), 1,
      anon_sym_if,
    ACTIONS(60), 1,
      anon_sym_range,
    ACTIONS(62), 1,
      sym_pipeline_stub,
    ACTIONS(64), 1,
      sym_comment,
    STATE(75), 1,
      sym__pipeline,
  [775] = 3,
    ACTIONS(110), 1,
      anon_sym_DASH2,
    ACTIONS(112), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(52), 1,
      sym__right_delimiter,
  [785] = 3,
    ACTIONS(114), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(77), 1,
      aux_sym_if_action_repeat1,
    STATE(79), 1,
      sym__left_delimiter,
  [795] = 3,
    ACTIONS(110), 1,
      anon_sym_DASH2,
    ACTIONS(116), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(48), 1,
      sym__right_delimiter,
  [805] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(120), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(7), 1,
      sym__right_delimiter,
  [815] = 2,
    ACTIONS(124), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(122), 2,
      ts_builtin_sym_end,
      sym_text,
  [823] = 2,
    ACTIONS(128), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      sym_text,
  [831] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(130), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(9), 1,
      sym__right_delimiter,
  [841] = 2,
    ACTIONS(134), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(132), 2,
      ts_builtin_sym_end,
      sym_text,
  [849] = 3,
    ACTIONS(110), 1,
      anon_sym_DASH2,
    ACTIONS(136), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(54), 1,
      sym__right_delimiter,
  [859] = 2,
    ACTIONS(140), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(138), 2,
      ts_builtin_sym_end,
      sym_text,
  [867] = 3,
    ACTIONS(110), 1,
      anon_sym_DASH2,
    ACTIONS(142), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(55), 1,
      sym__right_delimiter,
  [877] = 2,
    ACTIONS(146), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(144), 2,
      ts_builtin_sym_end,
      sym_text,
  [885] = 2,
    ACTIONS(150), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(148), 2,
      ts_builtin_sym_end,
      sym_text,
  [893] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(152), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(19), 1,
      sym__right_delimiter,
  [903] = 3,
    ACTIONS(110), 1,
      anon_sym_DASH2,
    ACTIONS(154), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(47), 1,
      sym__right_delimiter,
  [913] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(156), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(22), 1,
      sym__right_delimiter,
  [923] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(158), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(10), 1,
      sym__right_delimiter,
  [933] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(160), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(11), 1,
      sym__right_delimiter,
  [943] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(162), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(6), 1,
      sym__right_delimiter,
  [953] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(164), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(90), 1,
      sym__right_delimiter,
  [963] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(166), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(89), 1,
      sym__right_delimiter,
  [973] = 3,
    ACTIONS(110), 1,
      anon_sym_DASH2,
    ACTIONS(168), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(72), 1,
      sym__right_delimiter,
  [983] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(170), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(88), 1,
      sym__right_delimiter,
  [993] = 3,
    ACTIONS(110), 1,
      anon_sym_DASH2,
    ACTIONS(172), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(76), 1,
      sym__right_delimiter,
  [1003] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(174), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(17), 1,
      sym__right_delimiter,
  [1013] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(176), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(87), 1,
      sym__right_delimiter,
  [1023] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(178), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(86), 1,
      sym__right_delimiter,
  [1033] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(180), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(18), 1,
      sym__right_delimiter,
  [1043] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(182), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(85), 1,
      sym__right_delimiter,
  [1053] = 2,
    ACTIONS(186), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(184), 2,
      ts_builtin_sym_end,
      sym_text,
  [1061] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(188), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(8), 1,
      sym__right_delimiter,
  [1071] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(190), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(95), 1,
      sym__right_delimiter,
  [1081] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(192), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(94), 1,
      sym__right_delimiter,
  [1091] = 2,
    ACTIONS(196), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(194), 2,
      ts_builtin_sym_end,
      sym_text,
  [1099] = 3,
    ACTIONS(198), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(77), 1,
      aux_sym_if_action_repeat1,
    STATE(101), 1,
      sym__left_delimiter,
  [1109] = 3,
    ACTIONS(54), 1,
      anon_sym_elseif,
    ACTIONS(201), 1,
      anon_sym_else,
    ACTIONS(203), 1,
      anon_sym_end,
  [1119] = 3,
    ACTIONS(54), 1,
      anon_sym_elseif,
    ACTIONS(205), 1,
      anon_sym_else,
    ACTIONS(207), 1,
      anon_sym_end,
  [1129] = 3,
    ACTIONS(110), 1,
      anon_sym_DASH2,
    ACTIONS(209), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(50), 1,
      sym__right_delimiter,
  [1139] = 3,
    ACTIONS(118), 1,
      anon_sym_DASH2,
    ACTIONS(211), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(25), 1,
      sym__right_delimiter,
  [1149] = 2,
    ACTIONS(215), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(213), 2,
      ts_builtin_sym_end,
      sym_text,
  [1157] = 3,
    ACTIONS(114), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(77), 1,
      aux_sym_if_action_repeat1,
    STATE(78), 1,
      sym__left_delimiter,
  [1167] = 2,
    ACTIONS(217), 1,
      sym_pipeline_stub,
    STATE(56), 1,
      sym__pipeline,
  [1174] = 2,
    ACTIONS(148), 1,
      sym_text,
    ACTIONS(150), 1,
      anon_sym_LBRACE_LBRACE,
  [1181] = 2,
    ACTIONS(144), 1,
      sym_text,
    ACTIONS(146), 1,
      anon_sym_LBRACE_LBRACE,
  [1188] = 2,
    ACTIONS(138), 1,
      sym_text,
    ACTIONS(140), 1,
      anon_sym_LBRACE_LBRACE,
  [1195] = 2,
    ACTIONS(126), 1,
      sym_text,
    ACTIONS(128), 1,
      anon_sym_LBRACE_LBRACE,
  [1202] = 2,
    ACTIONS(122), 1,
      sym_text,
    ACTIONS(124), 1,
      anon_sym_LBRACE_LBRACE,
  [1209] = 2,
    ACTIONS(132), 1,
      sym_text,
    ACTIONS(134), 1,
      anon_sym_LBRACE_LBRACE,
  [1216] = 2,
    ACTIONS(219), 1,
      sym_pipeline_stub,
    STATE(70), 1,
      sym__pipeline,
  [1223] = 2,
    ACTIONS(221), 1,
      sym_pipeline_stub,
    STATE(67), 1,
      sym__pipeline,
  [1230] = 2,
    ACTIONS(213), 1,
      sym_text,
    ACTIONS(215), 1,
      anon_sym_LBRACE_LBRACE,
  [1237] = 2,
    ACTIONS(194), 1,
      sym_text,
    ACTIONS(196), 1,
      anon_sym_LBRACE_LBRACE,
  [1244] = 2,
    ACTIONS(184), 1,
      sym_text,
    ACTIONS(186), 1,
      anon_sym_LBRACE_LBRACE,
  [1251] = 2,
    ACTIONS(223), 1,
      sym_pipeline_stub,
    STATE(61), 1,
      sym__pipeline,
  [1258] = 2,
    ACTIONS(225), 1,
      sym_pipeline_stub,
    STATE(60), 1,
      sym__pipeline,
  [1265] = 1,
    ACTIONS(227), 1,
      anon_sym_RBRACE_RBRACE,
  [1269] = 1,
    ACTIONS(229), 1,
      anon_sym_RBRACE_RBRACE,
  [1273] = 1,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
  [1277] = 1,
    ACTIONS(54), 1,
      anon_sym_elseif,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 66,
  [SMALL_STATE(6)] = 88,
  [SMALL_STATE(7)] = 107,
  [SMALL_STATE(8)] = 126,
  [SMALL_STATE(9)] = 145,
  [SMALL_STATE(10)] = 164,
  [SMALL_STATE(11)] = 183,
  [SMALL_STATE(12)] = 202,
  [SMALL_STATE(13)] = 221,
  [SMALL_STATE(14)] = 240,
  [SMALL_STATE(15)] = 259,
  [SMALL_STATE(16)] = 278,
  [SMALL_STATE(17)] = 297,
  [SMALL_STATE(18)] = 316,
  [SMALL_STATE(19)] = 335,
  [SMALL_STATE(20)] = 354,
  [SMALL_STATE(21)] = 373,
  [SMALL_STATE(22)] = 392,
  [SMALL_STATE(23)] = 411,
  [SMALL_STATE(24)] = 430,
  [SMALL_STATE(25)] = 449,
  [SMALL_STATE(26)] = 468,
  [SMALL_STATE(27)] = 487,
  [SMALL_STATE(28)] = 512,
  [SMALL_STATE(29)] = 537,
  [SMALL_STATE(30)] = 552,
  [SMALL_STATE(31)] = 574,
  [SMALL_STATE(32)] = 586,
  [SMALL_STATE(33)] = 608,
  [SMALL_STATE(34)] = 620,
  [SMALL_STATE(35)] = 639,
  [SMALL_STATE(36)] = 648,
  [SMALL_STATE(37)] = 667,
  [SMALL_STATE(38)] = 686,
  [SMALL_STATE(39)] = 705,
  [SMALL_STATE(40)] = 724,
  [SMALL_STATE(41)] = 743,
  [SMALL_STATE(42)] = 759,
  [SMALL_STATE(43)] = 775,
  [SMALL_STATE(44)] = 785,
  [SMALL_STATE(45)] = 795,
  [SMALL_STATE(46)] = 805,
  [SMALL_STATE(47)] = 815,
  [SMALL_STATE(48)] = 823,
  [SMALL_STATE(49)] = 831,
  [SMALL_STATE(50)] = 841,
  [SMALL_STATE(51)] = 849,
  [SMALL_STATE(52)] = 859,
  [SMALL_STATE(53)] = 867,
  [SMALL_STATE(54)] = 877,
  [SMALL_STATE(55)] = 885,
  [SMALL_STATE(56)] = 893,
  [SMALL_STATE(57)] = 903,
  [SMALL_STATE(58)] = 913,
  [SMALL_STATE(59)] = 923,
  [SMALL_STATE(60)] = 933,
  [SMALL_STATE(61)] = 943,
  [SMALL_STATE(62)] = 953,
  [SMALL_STATE(63)] = 963,
  [SMALL_STATE(64)] = 973,
  [SMALL_STATE(65)] = 983,
  [SMALL_STATE(66)] = 993,
  [SMALL_STATE(67)] = 1003,
  [SMALL_STATE(68)] = 1013,
  [SMALL_STATE(69)] = 1023,
  [SMALL_STATE(70)] = 1033,
  [SMALL_STATE(71)] = 1043,
  [SMALL_STATE(72)] = 1053,
  [SMALL_STATE(73)] = 1061,
  [SMALL_STATE(74)] = 1071,
  [SMALL_STATE(75)] = 1081,
  [SMALL_STATE(76)] = 1091,
  [SMALL_STATE(77)] = 1099,
  [SMALL_STATE(78)] = 1109,
  [SMALL_STATE(79)] = 1119,
  [SMALL_STATE(80)] = 1129,
  [SMALL_STATE(81)] = 1139,
  [SMALL_STATE(82)] = 1149,
  [SMALL_STATE(83)] = 1157,
  [SMALL_STATE(84)] = 1167,
  [SMALL_STATE(85)] = 1174,
  [SMALL_STATE(86)] = 1181,
  [SMALL_STATE(87)] = 1188,
  [SMALL_STATE(88)] = 1195,
  [SMALL_STATE(89)] = 1202,
  [SMALL_STATE(90)] = 1209,
  [SMALL_STATE(91)] = 1216,
  [SMALL_STATE(92)] = 1223,
  [SMALL_STATE(93)] = 1230,
  [SMALL_STATE(94)] = 1237,
  [SMALL_STATE(95)] = 1244,
  [SMALL_STATE(96)] = 1251,
  [SMALL_STATE(97)] = 1258,
  [SMALL_STATE(98)] = 1265,
  [SMALL_STATE(99)] = 1269,
  [SMALL_STATE(100)] = 1273,
  [SMALL_STATE(101)] = 1277,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(4),
  [16] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(29),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_action_repeat1, 5, .production_id = 5),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(26),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__left_delimiter, 1),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__left_delimiter, 1),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__left_delimiter, 2),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__left_delimiter, 2),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_action, 8, .production_id = 3),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range_action, 8, .production_id = 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_action, 9, .production_id = 4),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_action, 9, .production_id = 4),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_action, 8, .production_id = 2),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_action, 8, .production_id = 2),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_action, 12, .production_id = 6),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_action, 12, .production_id = 6),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_action, 12, .production_id = 7),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range_action, 12, .production_id = 7),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_action, 13, .production_id = 8),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_action, 13, .production_id = 8),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_action, 3),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__comment_action, 3),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pipeline_action, 3),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__pipeline_action, 3),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_action_repeat1, 2, .production_id = 1), SHIFT_REPEAT(29),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__right_delimiter, 2),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__right_delimiter, 2),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [231] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_gotmpl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
